-- Recipient Inflow History: Aggregated inbound transfer patterns
-- Parameters: :recipient_id (INTEGER)

SELECT
    COUNT(*) AS TOTAL_INFLOW_COUNT,
    SUM(t.SOURCE_AMOUNT) AS TOTAL_INFLOW_VOLUME,
    AVG(t.SOURCE_AMOUNT) AS AVG_INFLOW_AMOUNT,
    COUNT(DISTINCT t.SENDER_ID) AS DISTINCT_SENDER_COUNT,
    MIN(t.CREATED_AT) AS FIRST_INFLOW_AT,
    MAX(t.CREATED_AT) AS LAST_INFLOW_AT,
    DATEDIFF('day', MIN(t.CREATED_AT), MAX(t.CREATED_AT)) AS INFLOW_SPAN_DAYS
FROM NGONAROID_FDS.FDS.TRANSACTIONS t
WHERE t.RECIPIENT_ID = :recipient_id
  AND t.STATUS IN ('FUNDED', 'COMPLETED', 'PROCESSING');
