-- Sender Behavioral Profile: Historical transaction patterns
-- Parameters: :sender_id (INTEGER)

WITH sender_txns AS (
    SELECT
        t.SOURCE_AMOUNT,
        t.TARGET_AMOUNT,
        t.RECIPIENT_ID,
        t.STATUS,
        t.CREATED_AT,
        EXTRACT(HOUR FROM t.CREATED_AT) AS TXN_HOUR
    FROM NGONAROID_FDS.FDS.TRANSACTIONS t
    WHERE t.SENDER_ID = :sender_id
      AND t.STATUS IN ('FUNDED', 'COMPLETED', 'PROCESSING')
),
hourly_dist AS (
    SELECT
        TXN_HOUR,
        COUNT(*) AS TXN_COUNT
    FROM sender_txns
    GROUP BY TXN_HOUR
),
top_recipients AS (
    SELECT
        r.NAME AS RECIPIENT_NAME,
        r.COUNTRY,
        COUNT(*) AS SEND_COUNT
    FROM sender_txns st
    JOIN NGONAROID_FDS.FDS.RECIPIENTS r ON st.RECIPIENT_ID = r.ID
    GROUP BY r.NAME, r.COUNTRY
    ORDER BY SEND_COUNT DESC
    LIMIT 5
)
SELECT
    COUNT(*) AS TOTAL_TXN_COUNT,
    SUM(SOURCE_AMOUNT) AS LIFETIME_VOLUME,
    AVG(SOURCE_AMOUNT) AS AVG_AMOUNT,
    STDDEV(SOURCE_AMOUNT) AS STDDEV_AMOUNT,
    MAX(SOURCE_AMOUNT) AS MAX_AMOUNT,
    MIN(SOURCE_AMOUNT) AS MIN_AMOUNT,
    COUNT(DISTINCT RECIPIENT_ID) AS UNIQUE_RECIPIENT_COUNT,
    DATEDIFF('day', MAX(CREATED_AT), CURRENT_TIMESTAMP()) AS DAYS_SINCE_LAST_TXN,
    (SELECT ARRAY_AGG(OBJECT_CONSTRUCT('hour', TXN_HOUR, 'count', TXN_COUNT))
     FROM hourly_dist) AS HOURLY_DISTRIBUTION,
    (SELECT ARRAY_AGG(OBJECT_CONSTRUCT('name', RECIPIENT_NAME, 'country', COUNTRY, 'count', SEND_COUNT))
     FROM top_recipients) AS TOP_RECIPIENTS
FROM sender_txns;
