-- Ngonaroid FDS: Snowflake Schema Setup
-- Creates the data model for fraud detection reasoning over transaction history

CREATE DATABASE IF NOT EXISTS NGONAROID_FDS;
CREATE SCHEMA IF NOT EXISTS NGONAROID_FDS.FDS;

USE SCHEMA NGONAROID_FDS.FDS;

-- Users table (mirrors remittance app users)
CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) DEFAULT 'user',
    KYC_STATUS VARCHAR(30) DEFAULT 'PENDING_SUBMISSION',
    KYC_DOCUMENT_TYPE VARCHAR(30),
    KYC_DOCUMENT_NUMBER VARCHAR(100),
    WALLET_BALANCE FLOAT DEFAULT 0.0,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Recipients table
CREATE TABLE IF NOT EXISTS RECIPIENTS (
    ID INTEGER PRIMARY KEY,
    SENDER_ID INTEGER NOT NULL REFERENCES USERS(ID),
    NAME VARCHAR(255) NOT NULL,
    BANK_NAME VARCHAR(255) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(100) NOT NULL,
    ROUTING_NUMBER VARCHAR(100),
    COUNTRY VARCHAR(100) NOT NULL,
    CURRENCY VARCHAR(10) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Transaction history table (append-only log of all remittances)
CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID INTEGER PRIMARY KEY,
    REFERENCE_NUMBER VARCHAR(50) NOT NULL,
    SENDER_ID INTEGER NOT NULL REFERENCES USERS(ID),
    RECIPIENT_ID INTEGER NOT NULL REFERENCES RECIPIENTS(ID),
    SOURCE_CURRENCY VARCHAR(10) NOT NULL,
    TARGET_CURRENCY VARCHAR(10) NOT NULL,
    SOURCE_AMOUNT FLOAT NOT NULL,
    TARGET_AMOUNT FLOAT NOT NULL,
    EXCHANGE_RATE FLOAT NOT NULL,
    FEE FLOAT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Fraud analysis log (results from each skill invocation)
CREATE TABLE IF NOT EXISTS FRAUD_ANALYSIS_LOG (
    ID INTEGER AUTOINCREMENT PRIMARY KEY,
    TXN_ID INTEGER NOT NULL REFERENCES TRANSACTIONS(ID),
    REFERENCE_NUMBER VARCHAR(50),
    SENDER_ID INTEGER,
    RECIPIENT_ID INTEGER,
    SOURCE_AMOUNT FLOAT,
    IS_FRAUD BOOLEAN,
    FRAUD_TYPE VARCHAR(100),
    ANOMALY_SCORE FLOAT,
    VELOCITY_FLAGS VARIANT,
    EVIDENCE VARIANT,
    EXPLANATION VARCHAR(4000),
    DECISION VARCHAR(20),
    ANALYZED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Stream on TRANSACTIONS for real-time FDS processing
CREATE STREAM IF NOT EXISTS TXN_STREAM ON TABLE TRANSACTIONS
    APPEND_ONLY = TRUE;

-- Pending transactions staging table (used by consumer polling)
CREATE TABLE IF NOT EXISTS PENDING_TRANSACTIONS (
    ID INTEGER AUTOINCREMENT PRIMARY KEY,
    TXN_ID INTEGER NOT NULL,
    REFERENCE_NUMBER VARCHAR(50),
    SENDER_ID INTEGER,
    RECIPIENT_ID INTEGER,
    SOURCE_CURRENCY VARCHAR(10),
    TARGET_CURRENCY VARCHAR(10),
    SOURCE_AMOUNT FLOAT,
    TARGET_AMOUNT FLOAT,
    EXCHANGE_RATE FLOAT,
    FEE FLOAT,
    STATUS VARCHAR(20),
    PROCESSED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Task to move new transactions from stream to pending queue
CREATE OR REPLACE TASK ENQUEUE_PENDING_TXN
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('TXN_STREAM')
AS
    INSERT INTO PENDING_TRANSACTIONS (TXN_ID, REFERENCE_NUMBER, SENDER_ID, RECIPIENT_ID,
        SOURCE_CURRENCY, TARGET_CURRENCY, SOURCE_AMOUNT, TARGET_AMOUNT,
        EXCHANGE_RATE, FEE, STATUS)
    SELECT ID, REFERENCE_NUMBER, SENDER_ID, RECIPIENT_ID,
        SOURCE_CURRENCY, TARGET_CURRENCY, SOURCE_AMOUNT, TARGET_AMOUNT,
        EXCHANGE_RATE, FEE, STATUS
    FROM TXN_STREAM;

ALTER TASK ENQUEUE_PENDING_TXN RESUME;
