profile:
  label: "Ngonaroid Client"
  description: "Ngonaroid FDS client application"
  icon: public/favicon.svg

launch:
  web:
    install: "npm install && npm run build"
    command: "node server.js"
