-- Compliance Export: Structured report of flagged transactions for a date range
-- Parameters: :start_date (DATE), :end_date (DATE)

SELECT
    f.ANALYZED_AT AS ANALYSIS_DATE,
    f.TXN_ID,
    f.REFERENCE_NUMBER,
    t.CREATED_AT AS TRANSACTION_DATE,
    u.FULL_NAME AS SENDER_NAME,
    u.EMAIL AS SENDER_EMAIL,
    u.KYC_STATUS AS SENDER_KYC,
    r.NAME AS RECIPIENT_NAME,
    r.BANK_NAME AS RECIPIENT_BANK,
    r.COUNTRY AS RECIPIENT_COUNTRY,
    t.SOURCE_CURRENCY,
    t.TARGET_CURRENCY,
    t.SOURCE_AMOUNT,
    t.TARGET_AMOUNT,
    f.FRAUD_TYPE,
    f.ANOMALY_SCORE,
    f.DECISION,
    f.VELOCITY_FLAGS,
    f.EVIDENCE,
    f.EXPLANATION
FROM NGONAROID_FDS.FDS.FRAUD_ANALYSIS_LOG f
JOIN NGONAROID_FDS.FDS.TRANSACTIONS t ON f.TXN_ID = t.ID
JOIN NGONAROID_FDS.FDS.USERS u ON f.SENDER_ID = u.ID
JOIN NGONAROID_FDS.FDS.RECIPIENTS r ON f.RECIPIENT_ID = r.ID
WHERE f.ANALYZED_AT BETWEEN :start_date AND :end_date
  AND f.DECISION IN ('FAILED', 'SUSPICIOUS')
ORDER BY f.ANOMALY_SCORE DESC, f.ANALYZED_AT;
