-- Fraud Summary Dashboard: Aggregate metrics over analysis log
-- No parameters required (operates over full history)

WITH summary AS (
    SELECT
        COUNT(*) AS TOTAL_ANALYZED,
        SUM(CASE WHEN IS_FRAUD THEN 1 ELSE 0 END) AS FRAUD_COUNT,
        SUM(CASE WHEN DECISION = 'SUSPICIOUS' THEN 1 ELSE 0 END) AS SUSPICIOUS_COUNT,
        SUM(CASE WHEN DECISION = 'FUNDED' THEN 1 ELSE 0 END) AS FUNDED_COUNT,
        ROUND(SUM(CASE WHEN IS_FRAUD THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 2) AS FRAUD_RATE_PCT,
        AVG(ANOMALY_SCORE) AS AVG_ANOMALY_SCORE
    FROM NGONAROID_FDS.FDS.FRAUD_ANALYSIS_LOG
),
by_type AS (
    SELECT
        FRAUD_TYPE,
        COUNT(*) AS TYPE_COUNT,
        AVG(ANOMALY_SCORE) AS AVG_SCORE
    FROM NGONAROID_FDS.FDS.FRAUD_ANALYSIS_LOG
    WHERE IS_FRAUD = TRUE
    GROUP BY FRAUD_TYPE
    ORDER BY TYPE_COUNT DESC
),
top_flagged_senders AS (
    SELECT
        f.SENDER_ID,
        u.FULL_NAME,
        u.EMAIL,
        COUNT(*) AS FRAUD_FLAG_COUNT,
        AVG(f.ANOMALY_SCORE) AS AVG_SCORE
    FROM NGONAROID_FDS.FDS.FRAUD_ANALYSIS_LOG f
    JOIN NGONAROID_FDS.FDS.USERS u ON f.SENDER_ID = u.ID
    WHERE f.IS_FRAUD = TRUE
    GROUP BY f.SENDER_ID, u.FULL_NAME, u.EMAIL
    ORDER BY FRAUD_FLAG_COUNT DESC
    LIMIT 10
),
by_decision AS (
    SELECT
        DECISION,
        COUNT(*) AS DECISION_COUNT,
        AVG(ANOMALY_SCORE) AS AVG_SCORE
    FROM NGONAROID_FDS.FDS.FRAUD_ANALYSIS_LOG
    GROUP BY DECISION
)
SELECT
    'summary' AS SECTION,
    s.*
FROM summary s
UNION ALL
SELECT
    'by_type' AS SECTION,
    bt.*,
    NULL, NULL, NULL, NULL
FROM by_type bt;
