-- High-Risk Entity Report: Identify suspicious accounts and mule patterns
-- No parameters required

-- Senders with multiple fraud flags
SELECT
    'REPEAT_FRAUD_SENDER' AS RISK_CATEGORY,
    f.SENDER_ID AS ENTITY_ID,
    u.FULL_NAME,
    u.EMAIL,
    COUNT(*) AS FLAG_COUNT,
    AVG(f.ANOMALY_SCORE) AS AVG_SCORE,
    ARRAY_AGG(DISTINCT f.FRAUD_TYPE) AS FRAUD_TYPES
FROM NGONAROID_FDS.FDS.FRAUD_ANALYSIS_LOG f
JOIN NGONAROID_FDS.FDS.USERS u ON f.SENDER_ID = u.ID
WHERE f.DECISION IN ('FAILED', 'SUSPICIOUS')
GROUP BY f.SENDER_ID, u.FULL_NAME, u.EMAIL
HAVING COUNT(*) >= 2
ORDER BY FLAG_COUNT DESC

UNION ALL

-- Potential mule recipients (5+ distinct senders)
SELECT
    'POTENTIAL_MULE' AS RISK_CATEGORY,
    r.ID AS ENTITY_ID,
    r.NAME AS FULL_NAME,
    CONCAT(r.BANK_NAME, ' - ', r.ACCOUNT_NUMBER) AS EMAIL,
    COUNT(DISTINCT t.SENDER_ID) AS FLAG_COUNT,
    NULL AS AVG_SCORE,
    ARRAY_AGG(DISTINCT u.FULL_NAME) AS FRAUD_TYPES
FROM NGONAROID_FDS.FDS.TRANSACTIONS t
JOIN NGONAROID_FDS.FDS.RECIPIENTS r ON t.RECIPIENT_ID = r.ID
JOIN NGONAROID_FDS.FDS.USERS u ON t.SENDER_ID = u.ID
WHERE t.CREATED_AT >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY r.ID, r.NAME, r.BANK_NAME, r.ACCOUNT_NUMBER
HAVING COUNT(DISTINCT t.SENDER_ID) >= 5

UNION ALL

-- Rapid onboarding: New accounts (7 days) with large transfers
SELECT
    'RAPID_ONBOARDING' AS RISK_CATEGORY,
    u.ID AS ENTITY_ID,
    u.FULL_NAME,
    u.EMAIL,
    COUNT(*) AS FLAG_COUNT,
    MAX(t.SOURCE_AMOUNT) AS AVG_SCORE,
    ARRAY_CONSTRUCT('Account age: ' || DATEDIFF('day', u.CREATED_AT, CURRENT_TIMESTAMP()) || ' days') AS FRAUD_TYPES
FROM NGONAROID_FDS.FDS.USERS u
JOIN NGONAROID_FDS.FDS.TRANSACTIONS t ON u.ID = t.SENDER_ID
WHERE u.CREATED_AT >= DATEADD('day', -7, CURRENT_TIMESTAMP())
  AND t.SOURCE_AMOUNT >= 500
GROUP BY u.ID, u.FULL_NAME, u.EMAIL
ORDER BY FLAG_COUNT DESC;
