-- Circular Transfer Trace: Map money flow patterns for a sender
-- Parameters: :sender_id (INTEGER)

WITH RECURSIVE money_flow AS (
    -- Base: Direct outbound from sender
    SELECT
        t.SENDER_ID AS FROM_USER,
        r.SENDER_ID AS TO_USER,
        t.SOURCE_AMOUNT,
        t.CREATED_AT,
        1 AS HOP_LEVEL,
        ARRAY_CONSTRUCT(t.SENDER_ID, r.SENDER_ID) AS PATH
    FROM NGONAROID_FDS.FDS.TRANSACTIONS t
    JOIN NGONAROID_FDS.FDS.RECIPIENTS r ON t.RECIPIENT_ID = r.ID
    WHERE t.SENDER_ID = :sender_id
      AND t.CREATED_AT >= DATEADD('day', -30, CURRENT_TIMESTAMP())
      AND t.STATUS IN ('FUNDED', 'COMPLETED', 'PROCESSING')

    UNION ALL

    -- Recursive: Follow the money
    SELECT
        t.SENDER_ID AS FROM_USER,
        r.SENDER_ID AS TO_USER,
        t.SOURCE_AMOUNT,
        t.CREATED_AT,
        mf.HOP_LEVEL + 1 AS HOP_LEVEL,
        ARRAY_APPEND(mf.PATH, r.SENDER_ID) AS PATH
    FROM money_flow mf
    JOIN NGONAROID_FDS.FDS.TRANSACTIONS t ON t.SENDER_ID = mf.TO_USER
    JOIN NGONAROID_FDS.FDS.RECIPIENTS r ON t.RECIPIENT_ID = r.ID
    WHERE mf.HOP_LEVEL < 4
      AND t.CREATED_AT >= DATEADD('day', -30, CURRENT_TIMESTAMP())
      AND t.STATUS IN ('FUNDED', 'COMPLETED', 'PROCESSING')
      AND NOT ARRAY_CONTAINS(r.SENDER_ID::VARIANT, mf.PATH)
)
SELECT
    PATH,
    HOP_LEVEL,
    SUM(SOURCE_AMOUNT) AS TOTAL_FLOW,
    COUNT(*) AS TXN_COUNT,
    CASE WHEN ARRAY_CONTAINS(:sender_id::VARIANT, ARRAY_SLICE(PATH, 1, ARRAY_SIZE(PATH)))
         THEN TRUE ELSE FALSE END AS IS_CIRCULAR
FROM money_flow
GROUP BY PATH, HOP_LEVEL
HAVING IS_CIRCULAR = TRUE
ORDER BY HOP_LEVEL, TOTAL_FLOW DESC;
