-- Transaction Deep Dive: Full context for a specific transaction
-- Parameters: :txn_id (INTEGER)

-- 1. Transaction details with fraud analysis
SELECT
    t.ID AS TXN_ID,
    t.REFERENCE_NUMBER,
    t.SOURCE_CURRENCY,
    t.TARGET_CURRENCY,
    t.SOURCE_AMOUNT,
    t.TARGET_AMOUNT,
    t.EXCHANGE_RATE,
    t.FEE,
    t.STATUS,
    t.CREATED_AT,
    f.IS_FRAUD,
    f.FRAUD_TYPE,
    f.ANOMALY_SCORE,
    f.VELOCITY_FLAGS,
    f.EVIDENCE,
    f.EXPLANATION,
    f.DECISION,
    f.ANALYZED_AT,
    u.FULL_NAME AS SENDER_NAME,
    u.EMAIL AS SENDER_EMAIL,
    u.KYC_STATUS AS SENDER_KYC,
    u.CREATED_AT AS SENDER_CREATED_AT,
    r.NAME AS RECIPIENT_NAME,
    r.BANK_NAME,
    r.COUNTRY AS RECIPIENT_COUNTRY
FROM NGONAROID_FDS.FDS.TRANSACTIONS t
LEFT JOIN NGONAROID_FDS.FDS.FRAUD_ANALYSIS_LOG f ON t.ID = f.TXN_ID
LEFT JOIN NGONAROID_FDS.FDS.USERS u ON t.SENDER_ID = u.ID
LEFT JOIN NGONAROID_FDS.FDS.RECIPIENTS r ON t.RECIPIENT_ID = r.ID
WHERE t.ID = :txn_id;
