-- Time-Based Evasion: Detect unusual hours and spacing patterns
-- Parameters: :sender_id (INTEGER), :txn_hour (INTEGER)

WITH recent_txns AS (
    SELECT
        CREATED_AT,
        EXTRACT(HOUR FROM CREATED_AT) AS TXN_HOUR,
        LAG(CREATED_AT) OVER (ORDER BY CREATED_AT) AS PREV_TXN_AT
    FROM NGONAROID_FDS.FDS.TRANSACTIONS
    WHERE SENDER_ID = :sender_id
      AND CREATED_AT >= DATEADD('day', -7, CURRENT_TIMESTAMP())
      AND STATUS IN ('FUNDED', 'COMPLETED', 'PROCESSING', 'PENDING')
    ORDER BY CREATED_AT DESC
),
spacing AS (
    SELECT
        DATEDIFF('minute', PREV_TXN_AT, CREATED_AT) AS MINUTES_BETWEEN,
        TXN_HOUR
    FROM recent_txns
    WHERE PREV_TXN_AT IS NOT NULL
)
SELECT
    :txn_hour BETWEEN 1 AND 5 AS UNUSUAL_HOURS,
    :txn_hour AS CURRENT_TXN_HOUR,
    (SELECT COUNT(*) FROM recent_txns WHERE TXN_HOUR BETWEEN 1 AND 5) AS NIGHTTIME_TXN_COUNT_7D,
    (SELECT AVG(MINUTES_BETWEEN) FROM spacing) AS AVG_SPACING_MINUTES,
    (SELECT STDDEV(MINUTES_BETWEEN) FROM spacing) AS STDDEV_SPACING_MINUTES,
    (SELECT COUNT(*) FROM spacing WHERE MINUTES_BETWEEN < 5) AS RAPID_SUCCESSION_COUNT;
