-- Active Wallet Freezes: View all currently frozen wallets
-- No parameters required

SELECT
    wf.ID AS FREEZE_ID,
    wf.USER_ID,
    u.FULL_NAME,
    u.EMAIL,
    wf.TXN_ID,
    wf.REASON,
    wf.FRAUD_TYPE,
    wf.ANOMALY_SCORE,
    wf.FROZEN_AT,
    wf.FREEZE_DURATION_HOURS,
    wf.EXPIRES_AT,
    DATEDIFF('hour', CURRENT_TIMESTAMP(), wf.EXPIRES_AT) AS HOURS_REMAINING,
    CASE
        WHEN wf.EXPIRES_AT <= CURRENT_TIMESTAMP() THEN 'EXPIRED_PENDING_CLEANUP'
        WHEN DATEDIFF('hour', CURRENT_TIMESTAMP(), wf.EXPIRES_AT) <= 6 THEN 'EXPIRING_SOON'
        ELSE 'ACTIVE'
    END AS FREEZE_STATUS
FROM SNOWFLAKE_LEARNING_DB.FDS.WALLET_FREEZE_LOG wf
JOIN SNOWFLAKE_LEARNING_DB.FDS.USERS u ON wf.USER_ID = u.ID
WHERE wf.STATUS = 'ACTIVE'
ORDER BY wf.FROZEN_AT DESC;
