-- KYC Re-Verification Queue Status
-- No parameters required

SELECT
    kq.ID AS QUEUE_ID,
    kq.USER_ID,
    u.FULL_NAME,
    u.EMAIL,
    u.KYC_STATUS AS CURRENT_KYC_STATUS,
    kq.TXN_ID,
    kq.PRIORITY,
    kq.REASON,
    kq.FRAUD_TYPE,
    kq.ANOMALY_SCORE,
    kq.QUEUED_AT,
    kq.STATUS,
    DATEDIFF('hour', kq.QUEUED_AT, CURRENT_TIMESTAMP()) AS HOURS_IN_QUEUE,
    CASE
        WHEN kq.PRIORITY = 'URGENT' AND DATEDIFF('hour', kq.QUEUED_AT, CURRENT_TIMESTAMP()) > 4 THEN 'SLA_BREACHED'
        WHEN kq.PRIORITY = 'HIGH' AND DATEDIFF('hour', kq.QUEUED_AT, CURRENT_TIMESTAMP()) > 24 THEN 'SLA_BREACHED'
        ELSE 'WITHIN_SLA'
    END AS SLA_STATUS
FROM SNOWFLAKE_LEARNING_DB.FDS.KYC_REVERIFICATION_QUEUE kq
JOIN SNOWFLAKE_LEARNING_DB.FDS.USERS u ON kq.USER_ID = u.ID
WHERE kq.STATUS = 'PENDING'
ORDER BY
    CASE kq.PRIORITY WHEN 'URGENT' THEN 1 WHEN 'HIGH' THEN 2 ELSE 3 END,
    kq.QUEUED_AT ASC;
