-- Unfreeze Wallet: Reverse a wallet freeze and log the reversal
-- Parameters: :user_id (INTEGER), :operator (VARCHAR)

UPDATE SNOWFLAKE_LEARNING_DB.FDS.WALLET_FREEZE_LOG
SET STATUS = 'REVERSED',
    UNFROZEN_AT = CURRENT_TIMESTAMP(),
    UNFROZEN_BY = :operator
WHERE USER_ID = :user_id
  AND STATUS = 'ACTIVE';

INSERT INTO SNOWFLAKE_LEARNING_DB.FDS.REMEDIATION_ACTIONS (
    TXN_ID, REFERENCE_NUMBER, SENDER_ID, ACTION_TYPE, RISK_TIER,
    ANOMALY_SCORE, FRAUD_TYPE, ACTION_DETAILS, STATUS, EXECUTED_AT
)
SELECT
    wf.TXN_ID,
    NULL,
    wf.USER_ID,
    'WALLET_UNFROZEN',
    'REVERSAL',
    wf.ANOMALY_SCORE,
    wf.FRAUD_TYPE,
    OBJECT_CONSTRUCT(
        'unfrozen_by', :operator,
        'original_freeze_at', wf.FROZEN_AT::VARCHAR,
        'freeze_duration_hours', wf.FREEZE_DURATION_HOURS
    ),
    'EXECUTED',
    CURRENT_TIMESTAMP()
FROM SNOWFLAKE_LEARNING_DB.FDS.WALLET_FREEZE_LOG wf
WHERE wf.USER_ID = :user_id
  AND wf.STATUS = 'REVERSED'
  AND wf.UNFROZEN_AT = (SELECT MAX(UNFROZEN_AT) FROM SNOWFLAKE_LEARNING_DB.FDS.WALLET_FREEZE_LOG WHERE USER_ID = :user_id);
